# Generated by Django 4.0 on 2021-12-14 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=32, verbose_name='Фамилия')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=32, verbose_name='Производитель')),
                ('model', models.CharField(max_length=32, verbose_name='Модель')),
                ('plate_number', models.CharField(max_length=10, verbose_name='Номерной знак')),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.driver')),
            ],
        ),
    ]
